[[section-introduction-and-goals]]
== Introduction and Goals

[role="arc42help"]
****
Describes the relevant requirements and the driving forces that software architects and development team must consider. These include

* underlying business goals, essential features and functional requirements for the system
* quality goals for the architecture
* relevant stakeholders and their expectations

*Requirements*

*Quality Goals*

** Runtime quality attributes

*** Performance:
*** Security:
*** Availability:
*** Usability:

** Non-runtime quality attributes

*** Modifiability:
*** Portability:
*** Reusability:
*** Testability:

** Business quality attributes

*** Cost:
*** Schedule:
*** Time-to-market:

*Stakeholders*

  ** Jose Emilio Labra Gayo: Have a functional application that satisfy the initial criteria
  ** Work Group: Develop a functional application taht works correctly and improve our knowledge about solid and 
              software arquitecture.
  ** Client: have a functional application that allows him to keep his personal data.

****
=== Requirements Overview

[role="arc42help"]
****
.Contents
Short description of the functional requirements, driving forces, extract (or abstract)
of requirements. Link to (hopefully existing) requirements documents
(with version number and information where to find it).

A decentralized system which provides the client to dont show his personal data to other users.

.Motivation
From the point of view of the end users a system is created or modified to
improve support of a business activity and/or improve the quality.

Allowing the user to have the control of his personal data and just share the data he wants.

.Form
Short textual description, probably in tabular use-case format.
If requirements documents exist this overview should refer to these documents.

Keep these excerpts as short as possible. Balance readability of this document with potential redundancy w.r.t to requirements documents.
****

=== Quality Goals

[role="arc42help"]
****
.Contents
The top three (max five) quality goals for the architecture whose fulfillment is of highest importance to the major stakeholders. We really mean quality goals for the architecture. Don't confuse them with project goals. They are not necessarily identical.

.Motivation
You should know the quality goals of your most important stakeholders, since they will influence fundamental architectural decisions. Make sure to be very concrete about these qualities, avoid buzzwords.
If you as an architect do not know how the quality of your work will be judged …

.Form
A table with quality goals and concrete scenarios, ordered by priorities
****

=== Stakeholders

[role="arc42help"]
****
.Contents
Explicit overview of stakeholders of the system, i.e. all person, roles or organizations that

* should know the architecture
* have to be convinced of the architecture
* have to work with the architecture or with code
* need the documentation of the architecture for their work
* have to come up with decisions about the system or its development

* Jose Emilio Labra Gayo: he should know the arquitecture of the system as well as how to work with it. He also
  need the documentation of the project.
  
* Work Group: The group knows everything about the system: how it works, which is the arquiecture, work with the code of 
  the application, make the documentation and make the decicions about the project but keeping the initial idea.
 
* Client: The client just need to know how it works, the objective of the client is to have a good-working application.

.Motivation
You should know all parties involved in development of the system or affected by the system.
Otherwise, you may get nasty surprises later in the development process.
These stakeholders determine the extent and the level of detail of your work and its results.

.Form
Table with role names, person names, and their expectations with respect to the architecture and its documentation.
****

[options="header",cols="1,2,2"]
|===
|Role/Name|Contact|Expectations
| _<Role-1>_ | _<Contact-1>_ | _<Expectation-1>_
| _<Role-2>_ | _<Contact-2>_ | _<Expectation-2>_
|===
