[[section-introduction-and-goals]]
== Introduction and Goals

[role="arc42help"]
****
Describes the relevant requirements and the driving forces that software architects and development team must consider. These include

* Underlying business goals, essential features and functional requirements for the system
* Quality goals for the architecture
* Relevant stakeholders and their expectations

[role="arc42help"]
****
=== Requirements Overview

We use solid for this application and design a decentralized chat that allows people to communicate people and not share this       personal data.

We develop this system to allow users to keep his personal data save in this computer so the data doesnt need to go to a server.

****

[role="arc42help"]
****
=== Quality Goals

** *Runtime Quality Attributes*

*** *Performance efficiency:* Shows the response of the system to performing certain actions for a certain period of time. This characteristic represents the performance relative to the amount of resources used under stated conditions. There are *two ways how to measure performance*:

* *Latency:* Time spent on responding to an event
* *Channel capacity:* The number of events that occur at a certain point in time.

*** *Scalability:* is the ability of the system to handle load increases without decreasing performance, or the possibility to rapidly increase the load. There are *two ways to improve scalability*:

* *Vertical:* To increase, we add more resources, such as memory, disks or processors into one system.
* *Horizontal:* We increase the number of computing units and divide the load.

*** *Interoperability:* Is an attribute of the system or part of the system that is responsible for its operation and the transmission of data and its exchange with other external systems. Naturally, there are a lot of *problems for interaction*:

*** *Manageability:* Defines how easy it is for system administrators to manage the application.

*** *Reliability:* Ability of a system to remain operational over time.

*** *Security:* Is responsible for the ability of the system to reduce the likelihood of malicious or accidental actions as well as the possibility of theft or loss of information. There are a number of measures that are used to protect systems: authentication, encryption, audit, and others. *Examples of this attribute in the work* of the system are:

* The ability of the system to detect DDoS attacks and respond to them.
* Restrictions of user access in accordance with authentication/authorization.
* Prevention of SQL injection.
* Encryption of passwords and content.
* Secure connection.

*** *Availability:* Proportion of time that the system is functional and working. Measured as a percentage of the total system downtime over a predefined period. *Important indicators* for this attribute are:

* Availability.
* Planned downtime.
* Time needed to update the software, and so on.

*** *Usability:* Is one of the most important attributes, because, unlike in cases with other attributes, users can see directly how well this attribute of the system is worked out. One of the key problems of usability is too much interaction or too many actions necessary to accomplish a task. Incorrect sequences of steps in multistage interfaces are also a problem of usability. Data elements and controls may be designed not according to the accepted patterns of user experience, which also complicates the interaction. Examples of *important indicators* for this attribute are:

* List of supported devices, OS versions, screen resolutions, and browsers and their versions.
* Elements that accelerate user interaction, such as “hot keys”, “lists of suggestions”, and so on.
* Average time a user needs to perform individual actions.
* Support of accessibility for people with disabilities.

** *Non-Runtime Quality Attributes*

*** *Modifiability:* Determines how many common changes need to be made to the system to make changes to each individual item. Ideal is the case where each change affects only one element.

*** *Portability:*  In high-level computer programming is the usability of the same software in different environments.

*** *Reusability:* Is a chance of using a component or system in other components/systems with small or no change. Allocation of responsibilities, modularization, decreasing of copy-paste are all about reusability. Copying code, or worse, using different components for the same result in different places, is one of the biggest problems of reusability.

*** *Maintainability:* Is the ability of the system to support changes. Changes can be related to new business requirements or correction of old errors and affect system components or separate methods. Also, maintainability affects the time needed to restore the system after a failure. Excessive dependencies between components have a very negative effect on maintainability.

*** *Conceptual integrity:* Defines the consistency and coherence of the overall design. Includes the way that components or modules are designed.

** *System Quality Attributes*

*** *Supportability:* Is the ability of the system to provide useful information for identifying and solving problems. 
*The main problems* in ensuring supportability can be addressed with the following means:

* *No diagnosis:* How the activity and performance of the system are controlled. This includes various types of logging.
* *No tools for troubleshooting:* This includes backups, various systems for creating snapshots of the system, and tools for auditing the system. When the system fails, it is always more pleasant to wait for an automatic restart than to solve the issue manually.
* *No health checking:* This includes a variety of systems for measuring compilation time, deployment time, database size, or mobile application size.

*** *Testability:* Shows how well the system allows performing tests, according to predefined criteria. In addition to testing performance, testability makes it possible to effectively divide the system into subsystems. The *main indicators* for this attribute are:

* Percentage of coverage with modular, integration, or unit tests.
* The final list of required test environments as well as the final list of used approaches to testing (manual/automatic, regression, integration, etc.).

** *Business Quality Attributes*

*** *Cost and benefit:* The development effort will naturally have a budget that must not be exceeded. Different architectures will yield different development costs.

*** *Rollout schedule:* If a product is to be introduced as base functionality with many features released later, the flexibility and customizability of the architecture are important.

*** *Time-to-market:* The development effort will naturally have a budget that must not be exceeded. Different architectures will yield different development costs.

|===
| Ref |Quality attribute       |Scenario | Priority
|  1  | Performance efficiency |          |
|  2  | Scalability            |          |
|  3  | Interoperability       |          |
|  4  | Managability           |          |
|  5  | Reliability            |          |
|  6  | Security               |          |
|  7  | Availability           |          |
|  8  | Usability              |          |
|  9  | Modifiability          |          |
| 10  | Portability            |          |
| 11  | Reusability            |          |
| 12  | Maintainability        |          |
| 13  | Conceptual integrity   |          |
| 14  | Supportability         |          |
| 15  | Testability            |          |
| 16  | Cost and benefit       |          |
| 17  | Rollout schedule       |          |
| 18  | Time-to-market         |          |
|===

****

[role="arc42help"]
****
=== Stakeholders

* *Jose Emilio Labra Gayo:* He should know the architecture and be convinced of it, and he also needs to know the doumentation about the project.

* *Teamwork:* Needs to know everything about the project and have the power to take decissions of how the project is gonna be manage.

* *Client:* The client just needs to know how the application works.


[options="header",cols="1,2,2"]
|===
|Stakeholder|Description| Expectations
| Jose Emilio Labra Gayo | Supervisor | This client expects improving our knowledge in solid and develop a funcional decentralized chat application
| Teamwork | Group developing the application | Develop a functional application that allow us to pass the course
| Client | People that is going to use the application | Have the possibility to chat with another people keeping his data save
|===

****
