[[section-architecture-constraints]]
== Architecture Constraints


[role="arc42help"]
****
.Contents
Any requirement that constrains software architects in their freedom of design and implementation decisions or decision about the development process. These constraints sometimes go beyond individual systems and are valid for whole organizations and companies.

.Motivation
Architects should know exactly where they are free in their design decisions and where they must adhere to constraints.
Constraints must always be dealt with; they may be negotiable, though.

.Form
Simple tables of constraints with explanations.
If needed you can subdivide them into
technical constraints, organizational and political constraints and
conventions (e.g. programming or versioning guidelines, documentation or naming conventions)

.Constraints Table
|===
|Constraint |Explanation

|We must follow the five principles of SOLID
|The five principles are: Single Responsibility, Open/Closed, Liskov Substitution, Interface Segregation and Dependency Inversion.

|The application must be decentralized
|Our goal is to have a decentralized chat, that consists in having separated personal data from apps.

|The application must be object-oriented
|We have to develop our project with object-oriented programming.

|===
****
