[[section-technical-risks]]
== Risks and Technical Debts
****
.*Database*
We had some problems at the time of decide which database we will use because not all of us has used the 
  same kind of databases

.*Solid*
This is something completely new for all of us, so we may need to spend quite some time 
in order to start managing everything correctly.

.*Angular*
We are not experts on angular since we are not used to use typescript in this kind or level , and apply this
language to the SOLID requirments its gonna be difficult.

.*Real time messaging*
When two people are online they should be able to establish real time communication, during the development
process we may have to deal with some problems we have never faced before using javascript

.*Delivering messages in the chat*
We may face some problems with the messaging system of the application, problems like... what
happens when we send a message to someone who is not online? where do we keep that
message so it does not get in conflict with the main goal (decentralization) and gets delivered once 
the other client connects?

.*Cucumber*
We never did any acceptance test so we have to get used to work with Cucumber.
****
