= dechat_en3a

image:https://travis-ci.org/Arquisoft/dechat_en3a.svg?branch=master["Build Status", link="https://travis-ci.org/Arquisoft/dechat_en3a"]
image:https://codecov.io/gh/Arquisoft/dechat_en3a/branch/master/graph/badge.svg["Codecov",link="https://codecov.io/gh/Arquisoft/dechat_en3a"]
image:https://coveralls.io/repos/github/Arquisoft/dechat_en3a/badge.svg["Coverage",link="https://coveralls.io/github/Arquisoft/dechat_en3a"]
image:https://api.codacy.com/project/badge/Grade/fc7dc1da60ee4e9fb67ccff782625794["Codacy code quality", link="https://www.codacy.com/app/jelabra/dechat_en3a?utm_source=github.com&utm_medium=referral&utm_content=Arquisoft/dechat_en3a&utm_campaign=Badge_Grade"]


== Build documentation

The documentation is done in http://asciidoc.org/[AsciiDoc]
using the https://arc42.org/[arc42] templates.
The source documents are located at
 https://github.com/Arquisoft/dechat_en3a/tree/master/src/docs[src/docs].

Using https://maven.apache.org/[Maven] and the
https://asciidoctor.org/[AsciiDoctor plugin] it is possible to generate
the documentation running:

----
mvn generate-resources
----

== Compile and run

The skeleton project is a simple
 https://spring.io/projects/spring-boot[Spring-boot] application which can be run as:

----
 mvn spring-boot:run
----

Once executed, the application should be available at: http://localhost:8080

== Testing

There are some simple Unit tests at:
 https://github.com/Arquisoft/dechat_en3a/tree/master/src/test[src/test].

There are also some
 https://cucumber.io/[Cucumber based tests]
 with a simple user story defined at:
 https://github.com/Arquisoft/dechat_en3a/tree/master/src/test/resources/features[src/test/resources/features].

To run tests execute:

----
mvn test
----

== Site documentation

The https://github.com/Arquisoft/dechat_en3a/tree/master/pom.xml[pom.xml] file
 has also been configured to generate site project documentation running:

----
mvn site
----
== Some useful links
I (Daniel) add here some links I think may be useful for the team during the development process:

* https://github.com/itsee/awesome-solid[Solid resources].
* https://inrupt.com/solid-app-listing[Solid App Listing].
* https://inrupt.net/[Prototype implementation of a Solid server(Inrupt)].
* https://github.com/solid/solid-spec[Solid specifications].
* https://solid.inrupt.com/docs/app-on-your-lunch-break[Solid app on lunch break].
* https://pheyvaer.github.io/solid-chess/[Solid chess].
* https://github.com/solid/query-ldflex[Navigate throught contents of pods].
* https://github.com/comunica/comunica[SPARQL queries over RDF content].
* https://github.com/weso/landportal-rdf-generator[RDF generator].


== Meeting day 1-31-2019
In today's class we were introduced to the proyect we will need to develop during the course.
We made some decisions:

 * We decided to use Javascript as the programming language.
 * We decided that the documentation will be done by every member of the team. 
 
== Meeting day 2-7-2019
We made some decisions:
 - We considered the future use of a NoSQL database.
 - We assigned certain part of the documentation to each of the members of the group:
 
     * Document_1 -> Vladislav Stelmakh and Alvaro Lucas.
     * Document_2 -> Fernando Ruiz.
     * Document_3 -> Not assigned yet.
     * Document_4 -> Daniel Llana and Pablo Martinez.

== Meeting day 2-13-2019
All the members were present during the meeting.
In today's reunion we dealed with the first 4 documents of the documentation. 

* *Document 1* was completed by Alvaro Lucas and Vladislav Stelmakh.  
* *Document 2* was completed by Fernando Ruiz.  
* *Document 3* will be completed by Fernando Ruiz and Pablo Martinez.
* In the last reunion we assigned *Document 4* to Daniel Llana and Pablo Martinez, but it will be 
completed by Daniel Llana.

We also researched information about SOLID and https://www.w3.org/RDF/[RDF]

== Meeting day 2-14-2019
All the members were present during the meeting.

* Today we created our SOLID Community accounts in order to manage pots.
* Also, we planned to adapt our current documentation to the contents seen yesterday in the theory class (quality attributes and design concepts).
* We considered the tool http://plantuml.com/es/[PlantUML] to create UML graphs/diagrams for the documentation.

== Meeting day 2-20-2019
All the members were present during the meeting.
We made some decisions:

- We assigned certain part of the documentation to each of the members of the group:
     * Document_6 -> Vladislav Stelmakh.
     * Document_7 -> Pablo Martinez.
     * Document_9 -> Fernando Ruiz.
     * Document_10 -> Pablo Martínez and Vladislav Stelmakh.
     * Document_11 -> Alvaro Lucas and Daniel Llana.
     * Document_12 -> Fernando Ruiz and Daniel Llana.
  
== Meeting day 2-21-2019
All the members were present during the meeting.

In today's class we evaluated the documentation that is being developed.
We realized that we had made some mistakes in the documentation so we need to fix them.
Conclusions:
     
 * Fix the broken documentation.
 * Start developing some code.
  
We have some usefull links at the beginig of this document that may be really helpful in the developing process.
