= dechat_en3a

image:https://travis-ci.org/Arquisoft/dechat_en3a.svg?branch=master["Build Status", link="https://travis-ci.org/Arquisoft/dechat_en3a"]
image:https://codecov.io/gh/Arquisoft/dechat_en3a/branch/master/graph/badge.svg["Codecov",link="https://codecov.io/gh/Arquisoft/dechat_en3a"]
image:https://coveralls.io/repos/github/Arquisoft/dechat_en3a/badge.svg["Coverage",link="https://coveralls.io/github/Arquisoft/dechat_en3a"]
image:https://api.codacy.com/project/badge/Grade/fc7dc1da60ee4e9fb67ccff782625794["Codacy code quality", link="https://www.codacy.com/app/jelabra/dechat_en3a?utm_source=github.com&utm_medium=referral&utm_content=Arquisoft/dechat_en3a&utm_campaign=Badge_Grade"]


== Build documentation

The documentation is done in http://asciidoc.org/[AsciiDoc]
using the https://arc42.org/[arc42] templates.
The source documents are located at
 https://github.com/Arquisoft/dechat_en3a/tree/master/src/docs[src/docs].

== Compile and run

* First, clone or download the project
* Then download the needed modules by running the following command:
----
npm run installPackages
----
* Finally, to run the application: ng serve (in localhost port 4200) or ng serve --open (automatically opens the broswer with the app running).


== Testing
The testing of the project is done via 
 https://cucumber.io/[Cucumber], based on user stories, such as those defined in the 
 https://github.com/Arquisoft/dechat_en3a/tree/master/e2e/src/features[features folder].
 To run the tests, if it has not been done before, you should download the needed dependencies executing the following command
----
npm run installTestDeps
----

Then, open a console and launch the application.

Finally, to run the tests open another console and execute the following commands:
----
npm run pretest
----

----
npm run test2
----

== Site documentation
https://arquisoft.github.io/dechat_en3a/

== Some useful links
I (Daniel) add here some links I think may be useful for the team during the development process:

* https://github.com/itsee/awesome-solid[Solid resources].
* https://inrupt.com/solid-app-listing[Solid App Listing].
* https://inrupt.net/[Prototype implementation of a Solid server(Inrupt)].
* https://github.com/solid/solid-spec[Solid specifications].
* https://solid.inrupt.com/docs/app-on-your-lunch-break[Solid app on lunch break].
* https://pheyvaer.github.io/solid-chess/[Solid chess].
* https://github.com/solid/query-ldflex[Navigate throught contents of pods].
* https://github.com/comunica/comunica[SPARQL queries over RDF content].
* https://github.com/weso/landportal-rdf-generator[RDF generator].
* https://github.com/pheyvaer/solid-chess[Solid chess github].
* https://angular.io/guide/quickstart[Getting started with Angular].
* https://github.com/solid/solid-tutorial-angular[SOLID Angular tutorial (example Apps)].
* https://solid.inrupt.com/docs/writing-solid-apps-with-angular[SOLID Apps with Angular].
* https://github.com/TechnionYP5777/SmartCity-Market/wiki/Integrating-Codecov-with-a-GitHub-project-(Coverage-tool)[Integrating Codecov in Github project].
* https://cucumber.io/[Cucumber, for testing].
* https://www.amadousall.com/angular-e2e-with-cucumber/[How to setup cucumber in angular project (from scratch)].
* https://github.com/bchinmz/protractor-cucumber[Integrating cucumber in angular project (our case)].
