= dechat_en3a

image:https://travis-ci.org/Arquisoft/dechat_en3a.svg?branch=master["Build Status", link="https://travis-ci.org/Arquisoft/dechat_en3a"]
image:https://codecov.io/gh/Arquisoft/dechat_en3a/branch/master/graph/badge.svg["Codecov",link="https://codecov.io/gh/Arquisoft/dechat_en3a"]
image:https://coveralls.io/repos/github/Arquisoft/dechat_en3a/badge.svg["Coverage",link="https://coveralls.io/github/Arquisoft/dechat_en3a"]
image:https://api.codacy.com/project/badge/Grade/fc7dc1da60ee4e9fb67ccff782625794["Codacy code quality", link="https://www.codacy.com/app/jelabra/dechat_en3a?utm_source=github.com&utm_medium=referral&utm_content=Arquisoft/dechat_en3a&utm_campaign=Badge_Grade"]


== Build documentation

The documentation is done in http://asciidoc.org/[AsciiDoc]
using the https://arc42.org/[arc42] templates.
The source documents are located at
 https://github.com/Arquisoft/dechat_en3a/tree/master/src/docs[src/docs].

== Compile and run

* First, clone or download the project
* Then download the needed modules by running the following command:
----
npm run installPackages
----
* Finally, to run the application: ng serve (in localhost port 4200) or ng serve --open (automatically opens the broswer with the app running).


== Testing

There are some simple Unit tests at:
 https://github.com/Arquisoft/dechat_en3a/tree/master/src/test[src/test].

There are also some
 https://cucumber.io/[Cucumber based tests]
 with a simple user story defined at:
 https://github.com/Arquisoft/dechat_en3a/tree/master/src/test/resources/features[src/test/resources/features].

== Site documentation
https://arquisoft.github.io/dechat_en3a/

== Some useful links
I (Daniel) add here some links I think may be useful for the team during the development process:

* https://github.com/itsee/awesome-solid[Solid resources].
* https://inrupt.com/solid-app-listing[Solid App Listing].
* https://inrupt.net/[Prototype implementation of a Solid server(Inrupt)].
* https://github.com/solid/solid-spec[Solid specifications].
* https://solid.inrupt.com/docs/app-on-your-lunch-break[Solid app on lunch break].
* https://pheyvaer.github.io/solid-chess/[Solid chess].
* https://github.com/solid/query-ldflex[Navigate throught contents of pods].
* https://github.com/comunica/comunica[SPARQL queries over RDF content].
* https://github.com/weso/landportal-rdf-generator[RDF generator].
* https://github.com/pheyvaer/solid-chess[Solid chess github].
* https://angular.io/guide/quickstart[Getting started with Angular].
* https://github.com/solid/solid-tutorial-angular[SOLID Angular tutorial (example Apps)].
* https://solid.inrupt.com/docs/writing-solid-apps-with-angular[SOLID Apps with Angular].
* https://github.com/TechnionYP5777/SmartCity-Market/wiki/Integrating-Codecov-with-a-GitHub-project-(Coverage-tool)[Integrating Codecov in Github project].



== Meeting day 1-31-2019
In today's class we were introduced to the proyect we will need to develop during the course.
We made some decisions:

 * We decided to use Javascript as the programming language.
 * We decided that the documentation will be done by every member of the team. 
 
== Meeting day 2-7-2019
We made some decisions:
 - We considered the future use of a NoSQL database.
 - We assigned certain part of the documentation to each of the members of the group:
 
     * Document_1 -> Vladislav Stelmakh and Alvaro Lucas.
     * Document_2 -> Fernando Ruiz.
     * Document_3 -> Not assigned yet.
     * Document_4 -> Daniel Llana and Pablo Martinez.

== Meeting day 2-13-2019
All the members were present during the meeting.
In today's reunion we dealed with the first 4 documents of the documentation. 

* *Document 1* was completed by Alvaro Lucas and Vladislav Stelmakh.  
* *Document 2* was completed by Fernando Ruiz.  
* *Document 3* will be completed by Fernando Ruiz and Pablo Martinez.
* In the last reunion we assigned *Document 4* to Daniel Llana and Pablo Martinez, but it will be 
completed by Daniel Llana.

We also researched information about SOLID and https://www.w3.org/RDF/[RDF]

== Meeting day 2-14-2019
All the members were present during the meeting.

* Today we created our SOLID Community accounts in order to manage pots.
* Also, we planned to adapt our current documentation to the contents seen yesterday in the theory class (quality attributes and design concepts).
* We considered the tool http://plantuml.com/es/[PlantUML] to create UML graphs/diagrams for the documentation.

== Meeting day 2-20-2019
All the members were present during the meeting.
We made some decisions:

- We assigned certain part of the documentation to each of the members of the group:
     * Document_6 -> Vladislav Stelmakh.
     * Document_9 -> Fernando Ruiz.
     * Document_10 -> Pablo Martínez and Vladislav Stelmakh.
     * Document_11 -> Alvaro Lucas and Daniel Llana.
     * Document_12 -> Fernando Ruiz and Daniel Llana.
  
== Meeting day 2-21-2019
All the members were present during the meeting.

In today's class we evaluated the documentation that is being developed.
We realized that we had made some mistakes in the documentation so we need to fix them.
Conclusions:
     
 * Fix the broken documentation.
 * Start developing some code.
  
We have some usefull links at the beginig of this document that may be really helpful in the developing process.

== Meeting day 2-28-2019
All the members were present during the meeting. 

Today we started the 'coding' phase, we researched information in order to start coding. 

Initially, we got https://angular.io/guide/quickstart[started with angular] and tested some aplications with angular just to get in touch with it.

We have some SOLID aplications using Angular in the useful links section of this document.

== Meeting day 03-04-2019
 
I added a basic login Angular-SOLID based application. 
See the following link for https://github.com/Inrupt-inc/generator-solid-angular[detailed explanation].
 
* First, we install the SOLID generator, we run npm install -g @inrupt/generator-solid-angular.
* Then we can create the application using the following command: yo @inrupt/solid-angular (install yeoman if needed).
* To run the application: ng serve (in localhost port 4200) or ng serve --open (automatically opens the broswer with the app running).

== Meeting day 03-07-2019

We have decided to implement the funcionality that allows a user sending messages to other users for the next week.

We have improved the login window.

We have decided to use "Codecov" to manage the coverage of the tested code.

We must take a look about the structure in Angular.

All the members of the group were present in the meeting.

== Meeting day 03-12-2019
* All the members of the group but Vladi were present in the meeting.

* Today we decided to take some measures in order to improve the interface design of the application.

* Also, we kept researching information on how to be able to send a message follownig the SOLID specifications.

* In order to do that we researched the useful links at the beginig of the document.

* An approach to the messaging system is being developed.

== Meeting day 03-13-2019
* All the members of the group where present in the meeting
* Today we decided to make some improvements in the application, basically in the interface design.
* We added some additional options such as settings and personalized some incons.
* Also, a messaging box was created but still cannot communicate with the user's POD.






